ember-config {
    host = 0.0.0.0
    port = 4041
}

kafka-config {
    bootstrap-servers = "localhost:9093"

    topic {
        name               = "people-topic"
        num-partitions     = 3
        replication-factor = 1
    }

    producer {
        client-id         = people-producer
        bootstrap-servers = ${kafka-config.bootstrap-servers}
    }

    consumer {
        group-id          = people-group
        bootstrap-servers = ${kafka-config.bootstrap-servers}
    }
}
